apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.1.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: quickstart
spec:
  version: 8.1.2
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
---
# apiVersion: agent.k8s.elastic.co/v1alpha1
# kind: Agent
# metadata:
#   name: quickstart
# spec:
#   version: 8.1.2
#   elasticsearchRefs:
#   - name: quickstart
#   daemonSet: {}
#   config:
#     inputs:
#       - name: system-1
#         revision: 1
#         type: system/metrics
#         use_output: default
#         meta:
#           package:
#             name: system
#             version: 0.9.1
#         data_stream:
#           namespace: default
#         streams:
#           - id: system/metrics-system.cpu
#             data_stream:
#               dataset: system.cpu
#               type: metrics
#             metricsets:
#               - cpu
#             cpu.metrics:
#               - percentages
#               - normalized_percentages
#             period: 10s